### ISSUE TITLE
Research retrieving top 5 rated from a column

### ISSUE THREAD

**Issue by GMorse19** [sei-uxdi-collab/work_from_roam-api#18]
The List view may call for retrieving info from the API on a top 5 results basis.

What's the best way to do this?
Maybe it should be done on the front-end?

Leads:
https://stackoverflow.com/questions/4186969/most-efficient-way-to-retrieve-top-x-records-using-rails

`:order` seems promising, possibly along with `counter_cache`?

https://apidock.com/rails/ActiveRecord/QueryMethods/order

**Comment by GMorse19** [comment]
When a user searches by a filter (i.e. bathrooms) the return could be a number of possibilities.

A. Return workspaces that are closest to current location.
B. Return workspaces within a certain radius that have the highest rating.
C. Return workspaces within a certain radius that have the highest rating AND have wifi.

Workspaces that have the highest overall rating containing all of the attributes that a user chooses. 

Do we care what the ratings of the attributes are?? 

What if the highest rated workspace having all of the attributes that a user chooses has one amenity that is very important to the user, but that amenity is rated very low while the other less important amenities are rated very high?

Do we limit the filters chosen and rate the importance of each filter chosen?

Lots of questions....

**Comment by chardbres** [comment]
I was thinking on this a bit last night, and now I think that it makes more sense to build in an Axios call on the filter component, rather than have it dynamically refresh it's state as the user changes filter settings. Basically, the user keys in a few selections, and then a button click will make the Axios call based on those criteria, returning like 5 options within X distance (specified by user) that can be browsed through in the ListView.

**Comment by chardbres** [comment]
Now for the specifics of this:
1. WiFi access is usually the most important criteria, so we can have a toggle in the filter that is preset to "yes." If the user doesn't need it, like if they just want a quiet coffee shop to read in, they can toggle this off.
2. Then, we have two options to handle the selection process, as I see it:
  2a. Have users make a bunch of selections based on the review criteria of each workspace. Then, we just make an Axios call and rank the workspaces on the total accumulated value of all the criteria.
  2b. Have users specify their top 3 priorities, then make the Axios call and assign a weight to each feature. Then, rank the workspaces on these weighting factors. So if the user places coffee as #1, multiply the rating average by 1.5, then if outlets is #2, multiply this average by 1.2, etc.

If that makes sense.....


> I was thinking on this a bit last night, and now I think that it makes more sense to build in an Axios call on the filter component, rather than have it dynamically refresh it's state as the user changes filter settings. Basically, the user keys in a few selections, and then a button click will make the Axios call based on those criteria, returning like 5 options within X distance (specified by user) that can be browsed through in the ListView.

**Comment by GMorse19** [comment]
Yeah. I think that makes sense. With this scenario, I think the info we are providing from the API with the last testing branch would suffice. Basically a Boolean for all filters, so we can check if the filter exists. Then an average for each filter. 

Do you think we can handle any other sorting logic on the front end?  I’m not 100% sure how to make the axios call.

**Comment by chardbres** [comment]
I feel like we must be able to do it on the front-end? I have to take a peek at the resources you referenced to see if those will do the trick, but otherwise I think we can just .map or sort them based on greatest -> least average, no?

> Yeah. I think that makes sense. With this scenario, I think the info we are providing from the API with the last testing branch would suffice. Basically a Boolean for all filters, so we can check if the filter exists. Then an average for each filter.
> 
> Do you think we can handle any other sorting logic on the front end? I’m not 100% sure how to make the axios call.

**Comment by chardbres** [comment]
In any case, I can try to tackle an initial filter component. I think it will be a fairly straightforward Axios call, and then in theory once I get a list of 5 workspaces I can stuff them into some kind of filterData state object, then link them up with the ListView?

**Comment by GMorse19** [comment]
Worked out some logic using 'scope' in the WorkSpace model. We have the ability to retrieve the top(x) WorkSpaces, in order, with the highest average ratings.

There is still a lot to figure out:
Is this going to be the best way to filter our columns?
Does it make sense to do it this way?
Can we limit the GET request to a certain number or area so as not to have to filter over a large number of workspaces? (maybe logic should go in controller?)
Maybe we should create a 'counter_cache'? But if our search is dependent on geolocation, this may not be wise.

More research...

**Comment by GMorse19** [comment]
Note: We probably want to order 'noise' by the lowest rating.

**Comment by chardbres** [comment]
After thinking about it a bit, this is how I think that we should handle this:
1. Limit the queried workspaces to within a half mile of the user's location, or a location that they set. To get fancy down the road, we can also allow the user to change the radius of search.
2. Within that area, order the top 5 workspaces by the criteria the user has set. Have them specify their top-3 attributes, and then order the workspaces by aggregate score.

This 2nd piece would have to be done on the back-end. Basically, the call comes in with the top-3 attributes selected, and we take the workspaces within the distance, multiply the top concern by x1.5, the middle concern by x1.2, and the 3rd concern by x1.0, then sum these values and return the top 5 spaces ordered by the total.

Does this make sense? Maybe the UI/UX team has more insight on this. The front-end components are set up already, I just need to know how to adjust them.
