### ISSUE TITLE
Security Concern: don't serialize user on work_spaces

### ISSUE THREAD

**Issue by asooge** [sei-uxdi-collab/work_from_roam-api#63]
work_space `user` is the creator of the workspace. This data should not be serialized on the workspace because: 1. we don't use/have a use for that data 2. this will expose private user data like `favorites`, `reviews` and `email`  to anyone who uses the app. 

![image](https://user-images.githubusercontent.com/34760728/83335557-b59f1400-a27b-11ea-8c03-958252068293.png)

**Comment by GMorse19** [comment]
Solely for console.log purposes.
